### PR TITLE
Bump OpenFisca-UK version

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
This PR should resolve issues around working with UK microdata: previously, whenever we made a breaking change to a dataset, everyone working from a previous dataset file found it no longer worked. But now, we've got a new way of handling things that I've tried to make as automatic as possible - bumping openfisca-uk should ensure that the correct dataset re-downloads from GCP or GH releases where necessary.

@rickecon @jdebacker @jpycroft

### CODE REVIEW

**Comment by jdebacker** [comment]
Other than the test failure with the `SynthFRS.save()` method, this looks good.

**Comment by nikhilwoodruff** [comment]
Also adding the version check here. @jdebacker I think this will fail this PR but work on future ones, because it compares any changes since the last published tag, but the repo doesn't have any tags yet. This action I've added will publish a new tag for every PR merge commit with the version name.

**Comment by jdebacker** [comment]
@nikhilwoodruff Thanks for this PR!

I'm seeing test failures on GH Actions and am getting them locally as well.  I changed all references to 2018 to 2019 in `test_get_micro_data.py` as it seemed that was raising errors in that no 2018 file seemed available to download.  Doing so fixed one error, but this remains:

```
(oguk-dev) jason.debacker@JDEBACKER-2 oguk % pytest tests/test_get_micro_data.py
/Users/jason.debacker/anaconda3/envs/oguk-dev/lib/python3.7/site-packages/pep8.py:110: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
=========================================================== test session starts ============================================================
platform darwin -- Python 3.7.10, pytest-5.4.3, py-1.11.0, pluggy-0.13.1
rootdir: /Users/jason.debacker/repos/OG-UK
plugins: xdist-2.5.0, anyio-3.5.0, forked-1.4.0, pep8-1.0.6
collected 3 items

tests/test_get_micro_data.py F..                                                                                                     [100%]

================================================================= FAILURES =================================================================
_________________________________________________________________ test_frs _________________________________________________________________

    def test_frs():
        """
        Check that setting `data` to 'frs' uses cps data
        """
        baseline = False
        start_year = 2019

        # create a parametric reform
        def lower_pa(parameters):
            parameters.tax.income_tax.allowances.personal_allowance.amount.update(
                period=2019, value=10000
            )
            return parameters

        class lower_personal_tax_allowance(Reform):
            def apply(self):
                self.modify_parameters(modifier_function=lower_pa)

        reform = lower_personal_tax_allowance

        calc_out = get_micro_data.get_calculator_output(
>           baseline, start_year, reform=reform, data="frs"
        )

tests/test_get_micro_data.py:47:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
get_micro_data.py:87: in get_calculator_output
    sim = Microsimulation(reform, **sim_kwargs)
../../../anaconda3/envs/oguk-dev/lib/python3.7/site-packages/openfisca_uk/tools/simulation.py:55: in __init__
    f"\nYear {year} not available in dataset {dataset.name}: \n\t* Download the dataset [y]\n\t* Use the synthetic FRS (and set default) [n]\n\nChoice: "
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_pytest.capture.DontReadFromInput object at 0x7faca85b9e10>, args = ()

    def read(self, *args):
        raise IOError(
>           "pytest: reading from stdin while output is captured!  Consider using `-s`."
        )
E       OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.

../../../anaconda3/envs/oguk-dev/lib/python3.7/site-packages/_pytest/capture.py:733: OSError
----------------------------------------------------------- Captured stdout call -----------------------------------------------------------

Year 2018 not available in dataset synth_frs:
	* Download the dataset [y]
	* Use the synthetic FRS (and set default) [n]

Choice:

========================================================= short test summary info ==========================================================
FAILED tests/test_get_micro_data.py::test_frs - OSError: pytest: reading from stdin while output is captured!  Consider using `-s`.
================================================= 1 failed, 2 passed, 6 warnings in 9.89s ==================================================
(oguk-dev) jason.debacker@JDEBACKER-2 oguk % pytest tests/test_run_example.py
```

I'm unsure what the traceback in telling me since the start year is 2019, so I don't know where the warning about 2018 not being available is coming from.  What do you think?

**Comment by nikhilwoodruff** [comment]
Thanks @jdebacker - just took a look. I've changed all 2018 references to 2019 like you, and the GH action now seems to pass without errors - I wonder if [my changes](https://github.com/PSLmodels/OG-UK/pull/39/commits/a67261e2a3bdd7c9f9a673e5874fc3488cff38dc) are the same as yours?

**Comment by jdebacker** [comment]
This is great @nikhilwoodruff!  Those changes look like mine.  Tests are passing here, so I'll merge now. Thanks!

**Pull request merged**
