### PR TITLE
Updates for tax function estimation

### PR DESCRIPTION
**Pull request by jdebacker**
This PR makes some updates to the `Calibration` class (commenting out attributes not yet created) and to `get_micro_data.py` (to choose the proper weight from the FRS data and to set 2021 as the default start and end year).

### CODE REVIEW

**Comment by jdebacker** [comment]
I've added an example run script to this PR and a unit test to ensure it runs for at least 5 min.

I was successfully able to solve the model under the baseline and reform used in the `run_og_uk.py` script.

@rickecon @jpycroft I believe this PR is ready for your review.

**Comment by nikhilwoodruff** [comment]
Hi @jdebacker - just tried to run this but it doesn't seem to solve for me - I get a runtime error ("Steady state equilibrium not found") after about 2 minutes. Could this be a dependency issue, or something wrong in my setup?

**Comment by jdebacker** [comment]
@nikhilwoodruff Thanks for testing this out!

Your traceback doesn't sound like a dependency issue since things got kicked off and ran.  Unfortunately, I cannot replicate your result. 

It's possible this is related to a difference in dependent package versions.  Can you post the results of a `conda list` when you are in the `oguk-calibrate-dev` environment?

Also, what OS are you running?

**Comment by nikhilwoodruff** [comment]
The only thing I can think I've done differently in the setup is that I had to download the OG-USA source code from GitHub and install that, commenting out the OGUSA requirement in the environment.yml file - git refused to clone the repo, kept running into 'remote hung up unexpectedly' errors. But since both pointing at the latest version I assumed it would be fine. My conda list output is [here](https://gist.github.com/2d53536d74837691946fcbe334f06a48), and the output from run_og_uk.py is [here](https://gist.github.com/nikhilwoodruff/228eee89e829baf7cd8a5d823d28510c) if that helps? I'm on Ubuntu. Thanks!

**Comment by jdebacker** [comment]
@nikhilwoodruff @jpycroft Note that I just added the test of the `run_og_uk.py` script to the CI tests run on GH Actions.  The test passes, which means that all dependencies were installed fine on the machines used by GH Actions.  I don't know if looking through [the log files](https://github.com/PSLmodels/OG-UK/pull/19/checks?check_run_id=2820259501) from these runs would be helpful.

**Comment by nikhilwoodruff** [comment]
Thanks @jdebacker - I've still not figured out what the issue is on my end, but it's good to know it runs fine in the cloud. Out of interest are you running on the actual FRS microdata (the GH action runs on the toy dataset, and I'm running on the actual 2018 FRS)?

**Comment by jdebacker** [comment]
@nikhilwoodruff Maybe I've never run on the full FRS.  I've only done what you see in this PR.  I think that is all the model is set up to do.  The relevant line is [here](https://github.com/PSLmodels/OG-UK/blob/170351fe1a74b7a4a7bed60050a22822d585c315/og_uk_calibrate/get_micro_data.py#L43).  Please feel free to suggest and edit to this to use the full data (if it is available to the public).

**Pull request merged**
