### PR TITLE
LICENSE.md and OG-UK logo files

### PR DESCRIPTION
**Pull request by rickecon**
This PR does the following minor things:
* Adds and open source license in `LICENSE.md`
* Adds logos in a `docs/` directory that can be used for the documentation. Below is the `OG-UK_logo_long.png` logo.
OG-UK_logo_long
* Adds a `docs/README.md` file that discusses Jupyter Book documentation (to come) and how the logo files are created.

@jdebacker

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker I am working on getting `codecov` set up (see Issue #8) and waiting for @MattHJensen to give me the organizational credentials for this repo and `OG-USA-Calibration` to be able to set the webhooks and secrets in the Settings tab. In the meantime, this PR is ready to be reviewed and merged, and I can do the `codecov` updates in a separate PR. Otherwise, I 'll put the `codecov` updates in this PR.

**Comment by jdebacker** [comment]
Thanks for this @rickecon!  I do have an open PR the that adds tests and the CI testing action but that PR is still on going (need to finalize tests) so we could merge this in the meantime. 

I would suggest leaving code coverage reports off until the project is more mature. Else there could be lots of failed tests we have to ignore as it's built out.

**Comment by rickecon** [comment]
Ah, @jdebacker. I see your PR #2 that has the testing capability. I hadn't reviewed that yet because it wasn't passing the tests. Looks like there is an error with the GitHub action for testing that installs miniconda.
```
Error: The process '/usr/share/miniconda/condabin/conda' failed with exit code 1
```
Do you want me to review your PR first, then adapt my PR once yours is merged? Sorry I missed that.

**Comment by jdebacker** [comment]
@rickecon I was having trouble with tests on Python 3.8 and 3.9 with OpenFisca-UK.  OpenFisca-core is only tested against 3.7, so in PR #2, I only test this repo against that version of Python.

Maybe you can remove the testing files from this PR and just keep in the license and doc files?  I'll continue to work on PR #2, which adds CI testing along with substantive tests of `get_micro_data.py` and `txfunc.py`.

**Comment by rickecon** [comment]
I just removed `codecov.yml`, `build_and_test.yml`, and the `tests/`directory with the placeholder testing file `test_junk.py`. The testing files are incorporated in @jdebacker's PR #2, which is almost ready to be merged. And we decided not to add `codecov` until the repository is more mature.

**Comment by rickecon** [comment]
@jdebacker This PR is ready for review and merge. It really only has the `LICENSE.md` file, three logo `.png` files, and a `README.md` about Jupyter Book documentation (to come) and how the logo files were created.

**Comment by jdebacker** [comment]
LGTM - thanks @rickecon

**Pull request merged**
